<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.epyPhIQ' shared service.

return $this->privates['.service_locator.epyPhIQ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['mat_generator' => function (): \App\Utule\MatriculeGenerator {
    return ($this->privates['App\\Utule\\MatriculeGenerator'] ?? $this->load('getMatriculeGeneratorService.php'));
}, 'medecinRepos' => function (): \App\Repository\MedecinsRepository {
    return ($this->privates['App\\Repository\\MedecinsRepository'] ?? $this->load('getMedecinsRepositoryService.php'));
}]);
