<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\AdminController::addmedecin' => function () {
    return ($this->privates['.service_locator.epyPhIQ'] ?? $this->load('get_ServiceLocator_EpyPhIQService.php'));
}, 'App\\Controller\\AdminController::addservice' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController::addspecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController::deletemedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController::deletespecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController::editemedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController::editeservice' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController::editespecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController::showMedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController::showService' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController::showSpecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController:addmedecin' => function () {
    return ($this->privates['.service_locator.epyPhIQ'] ?? $this->load('get_ServiceLocator_EpyPhIQService.php'));
}, 'App\\Controller\\AdminController:addservice' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController:addspecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController:deletemedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController:deletespecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController:editemedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController:editeservice' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController:editespecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}, 'App\\Controller\\AdminController:showMedecin' => function () {
    return ($this->privates['.service_locator.RyPSmNk'] ?? $this->load('get_ServiceLocator_RyPSmNkService.php'));
}, 'App\\Controller\\AdminController:showService' => function () {
    return ($this->privates['.service_locator.NZOc7Gf'] ?? $this->load('get_ServiceLocator_NZOc7GfService.php'));
}, 'App\\Controller\\AdminController:showSpecialite' => function () {
    return ($this->privates['.service_locator.0rWuTMu'] ?? $this->load('get_ServiceLocator_0rWuTMuService.php'));
}])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
