<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utule\MatriculeGenerator' shared autowired service.

include_once $this->targetDirs[3].'/src/Utule/MatriculeGenerator.php';

return $this->privates['App\\Utule\\MatriculeGenerator'] = new \App\Utule\MatriculeGenerator(($this->privates['App\\Repository\\MedecinsRepository'] ?? $this->load('getMedecinsRepositoryService.php')));
