<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RyPSmNk' shared service.

return $this->privates['.service_locator.RyPSmNk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['repos' => function (): \App\Repository\MedecinsRepository {
    return ($this->privates['App\\Repository\\MedecinsRepository'] ?? $this->load('getMedecinsRepositoryService.php'));
}]);
