<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NZOc7Gf' shared service.

return $this->privates['.service_locator.NZOc7Gf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['repos' => function (): \App\Repository\ServicesRepository {
    return ($this->privates['App\\Repository\\ServicesRepository'] ?? $this->load('getServicesRepositoryService.php'));
}]);
