<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxFex0N\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxFex0N/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXxFex0N.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXxFex0N\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXxFex0N\srcDevDebugProjectContainer([
    'container.build_hash' => 'XxFex0N',
    'container.build_id' => '5a530de4',
    'container.build_time' => 1577792804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxFex0N');
